#image: node:latest
#juanje/angular-cli-chrome
#image: pipekung/angular:latest
#image: efgiese/efgiese-angular-chrome-headless

stages:

  - build
  
  - test

#cache: 
#  paths: 
#    - node_modules

#install_dependencies:
#  stage: build
 # script:
  # - npm install client/
   #- npm rm -rf node_modules
   

  #artifacts:
   # paths:
    #  - node_modules

#Lösningsförslag: artifacts eller caching för att spara över det som lagras i dependencies-staget?


#before_script: 
 # - chmod 0777 ./node_modules/.bin/ng
dependencies: 
  stage: build
  image: angular/ngcontainer
  script: 
  - cd client
  - npm ci
  - npm install apt 
#  - npm audit fix --force
  - npm install apt-get
  #- npm install -g @angular/cli
  #Här behövs angular/ngcontainer
  #stod sudo här tidigare
  - sudo apt-get update
  - sudo apt install chromium 
  cache:
    key: build-cache
    paths: 
    - client/

testing_testing:
 # image: browserless/chrome
  image: node:latest
  stage: test
 # before_script:
 # - export CHROME_BIN=/usr/bin/google-chrome
  script: 
  #- sudo npm install -g karma-cli
  #- karma start
  #- npm install karma-firefox-launcher --save-dev


  #- RUN apt-get install chromium -y
#  - npm i chromium
  # Här behövs senaste node
  - cd client
  - node -v
  - export CHROME_BIN='/usr/bin/chromium'
  - npm test
  cache:
    key: build-cache
    paths: 
    - client/
