#image: node:latest
image: angular/ngcontainer

stages:

  #- build
  
  - test

#cache: 
#  paths: 
#    - node_modules

#install_dependencies:
#  stage: build
 # script:
  # - npm install client/
   #- npm rm -rf node_modules
   

  #artifacts:
   # paths:
    #  - node_modules

#before_script: 
 # - chmod 0777 ./node_modules/.bin/ng

testing_testing:
 # image: browserless/chrome
  stage: test
 # before_script:
 # - export CHROME_BIN=/usr/bin/google-chrome
  script: 
  #- sudo npm install -g karma-cli
  #- karma start
  #- npm install karma-firefox-launcher --save-dev
  - cd client
  - npm ci
  - npm install apt
  - npm install -g @angular/cli
  - sudo apt -get clean 
  - sudo apt install chromium 
  #- RUN apt-get install chromium -y
#  - npm i chromium
  - npm test
