image: node:16-alpine3.11
#image: angular/ngcontainer

stages:

  #- build
  
  - test

#cache: 
#  paths: 
#    - node_modules

#install_dependencies:
#  stage: build
 # script:
  # - npm install client/
   #- npm rm -rf node_modules
   

  #artifacts:
   # paths:
    #  - node_modules

#before_script: 
 # - chmod 0777 ./node_modules/.bin/ng

testing_testing:
 # image: browserless/chrome
  stage: test
  before_script:
  - export CHROME_BIN=/usr/bin/google-chrome
  script: 
  - cd client
  #- sudo npm install -g karma-cli
  #- karma start
  #- npm install karma-firefox-launcher --save-dev
  - npm ci
  - npm install -g @angular/cli
  - npm test
