
stages:
  
  - test

testing_testing:
  image: node:lts-bullseye
  stage: test
  script: 
    - apt-get update
    - apt install -y chromium 
    

    - cd client
    - npm ci
  
    - npm install -g @angular/cli
    #Här behövs angular/ngcontainer
    #stod sudo här tidigare

    - export CHROME_BIN='/bin/chromium'

    - node -v
    - npm test --browsers=Headless --no-watch

