image: node:16-alpine3.11

stages:

  - build
  
  - test

cache: 
  paths: 
    - node_modules

install_dependencies:
  stage: build
  script:
   - npm install client/
   - npm rm -rf node_modules
   - npm install -g @angular/cli

  artifacts:
    paths:
      - node_modules

before_script: 
  - chmod 0777 * 

testing_testing:
  stage: test

  script: 
  - chmod npm test -- --browsers=ChromeHeadless --watch=false
