image: node:16-alpine3.11

stages:

  - build
  
  - test

cache: 
  paths: 
    - ./node_modules/.bin/ng

install_dependencies:
  stage: build
  script:
   - npm install client/
  artifacts:
    paths:
      - ./node_modules/.bin/ng

testing_testing:
  before_script: chmod 0777 ./node_modules/.bin/ng
  stage: test
  script: ./client npm test