image: efgiese/efgiese-angular-chrome-headless

stages:
  - setup
  - test

setup:
  stage: setup
  script:
    - npm prune
    - npm install

test_karma:
  stage: test
  script:
    - ./node_modules/@angular/cli/bin/ng test --browsers ChromeHeadless --watch=false
