image: node:16-alpine3.11
image: angular/ngcontainer

stages:

  - build
  
  - test

cache: 
  paths: 
    - ./node_modules/.bin/ng

install_dependencies:
  stage: build
  script:
   - npm install client/
  artifacts:
    paths:
      - ./node_modules/.bin/ng

#before_script: 
#  - chmod 0777 client/node_modules/.bin/ng

testing_testing:
  stage: test

  script: 
  - cd client
  - npm test
