image: node:16-alpine3.11

stages:

  - build
  
  - test

cache: 
  paths: 
    - .client/node_modules/

install_dependencies:
  stage: build
  script:
   - npm install
  artifacts:
    paths:
      - .client/node_modules/

testing_testing:
  stage: test
  script: npm test