version: '3' # specify docker-compose version
 
# Define the services/containers to be run
services:
 client:
   build: ./client
   ports:
     - "80:4200"
     - "9229:9229"
   volumes:
      - ./client:/usr/src/app
      - ./client/node_modules:/usr/src/app/node_modules
 server: # name of the first service
    build: ./server # specify the directory of the Dockerfile
    ports:
     - "8080:8080"
    environment:
     - MONGO_URL=mongodb://database/mean-app
    volumes:
     - ./server:/usr/src/app
     - ./server/node_modules:/usr/src/app/node_modules
    links:
     - database
    depends_on:
     - database
    command: npm run debug
 database: # name of the third service
   image: mongo # specify image to build container from
   volumes:
     - mongodb:/data/db
     - mongodb_config:/data/configdb
   ports:
     - "27017:27017" # specify port forewarding
volumes:
  mongodb:
  mongodb_config: